- .github/workflows/ci.yml
- backend/grpc-server/src/app.rs
- backend/grpc-server/tests/common.rs
- backend/grpc-server/tests/test_health.rs
- sdk/rust-grpc-client/src/lib.rs
fix: add protoc installation in ci
> fix: add protoc installation in ci

- Cargo.lock
- backend/connector-integration/Cargo.toml
- backend/connector-integration/src/connectors.rs
- backend/connector-integration/src/connectors/adyen.rs
- backend/connector-integration/src/connectors/adyen/transformers.rs
- backend/connector-integration/src/connectors/macros.rs
- backend/connector-integration/src/connectors/razorpay.rs
- backend/connector-integration/src/connectors/razorpay/transformers.rs
- backend/connector-integration/src/types.rs
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
Added Macros and Implemented Adyen Authorize flow using macros.
> feat(core): Added macros and Adyen authorize with macros

- backend/connector-integration/src/connectors/adyen.rs
- backend/connector-integration/src/connectors/adyen/transformers.rs
- backend/connector-integration/src/connectors/razorpay.rs
- backend/domain_types/src/connector_flow.rs
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
- backend/external-services/src/service.rs
- backend/grpc-api-types/proto/payment.proto
- backend/grpc-server/src/server/payments.rs
Added Submit evidence (L2) and Submit evidence for Adyen (L3)
```grpcurl -plaintext \
-H 'x-connector: adyen' \
-H 'x-auth: signature-key' \
-H 'x-api-key: API_KEY' \
-H 'x-key1: KEY!' \
-H 'x-api-secret: API_SECRET' \
-d '  {
"connector_dispute_id" :"VNW4LBTMHCJXKN75",
"merchant_account_id":"account_id",
"receipt":"/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/wAALCAABAAEBAREA/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AKp//2Q==",
"receipt_file_type":"image/jpeg"
}
' \
localhost:8000 ucs.payments.PaymentService/SubmitEvidence
```
Response
```
{
"dispute_status": "DisputeChallenged",
"connector_dispute_id": "VNW4LBTMHCJXKN75"
}
```
> feat(core): Added Submit evidence (L2) and Submit evidence for Adyen (L3)

- examples/example-rs/Cargo.toml
- examples/example-rs/README.md
- examples/example-rs/src/main.rs
- sdk/rust-grpc-client/README.md
- sdk/rust-grpc-client/src/lib.rs
- The rust client library was not exposing top level modules which were required for request and response types impors.
- Update the `example-rs` too
by using it in local with hyperswitch
> fix(core): fixed the rust client library and its usage

- backend/domain_types/src/errors.rs
- backend/grpc-server/src/error.rs
- backend/grpc-server/src/server/payments.rs
- backend/grpc-server/src/utils.rs
Added the IntoGrpcStatus and ErrorSwitch Traits and the corresponding implementations for these traits.
**Payment Authorize (Happy Case)**
-Request
```
grpcurl -plaintext \
-H 'x-connector: adyen' \
-H 'x-auth: signature-key' \
-H 'x-api-key: API_KEY' \
-H 'x-key1: KEY1' \
-H 'x-api-secret: API_SECRET' \
-d '{
"amount": 1000,
"currency": "USD",
"payment_method": "CARD",
"payment_method_data": {
"card": {
"card_number": "4166676667666746",
"card_exp_month": "03",
"card_exp_year": "2030",
"card_cvc": "737"
}
},
"connector_customer": "abc123",
"return_url": "www.google.com",
"address": {},
"auth_type": "THREE_DS",
"connector_request_reference_id": "ref_12345",
"enrolled_for_3ds": true,
"request_incremental_authorization": false,
"minor_amount": 1000,
"browser_info": {
"user_agent": …
```
> feat(core): Implement Error Framework

- backend/connector-integration/src/connectors/adyen.rs
- backend/connector-integration/src/connectors/adyen/transformers.rs
Added Macros for all the flows of Adyen.
> feat(connector): Added macros for adyen flows

- connector_integration_macros.md
- macro_framework.md
Connector Integration With Macros Guide
> feat(docs): Connector Integration With Macros Guide Doc

- Cargo.lock
- backend/connector-integration/src/connectors/adyen.rs
- backend/connector-integration/src/connectors/razorpay.rs
- backend/domain_types/Cargo.toml
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
Migrated the ConnectorSpecifications and ConnectorValidations trait from Hyperswitch to Connector-Service and implemented them for Adyen and Razorpay Connectors.
> feat(core): [ADYEN, RAZORPAY] Added util functions for Connector Specifications & Validations

- .typos.toml
- Cargo.lock
- backend/connector-integration/Cargo.toml
- backend/connector-integration/src/connectors.rs
- backend/connector-integration/src/connectors/adyen/test.rs
- backend/connector-integration/src/connectors/elavon.rs
- backend/connector-integration/src/connectors/elavon/transformers.rs
- backend/connector-integration/src/connectors/razorpay/test.rs
- backend/connector-integration/src/types.rs
- backend/connector-integration/src/utils.rs
- backend/connector-integration/src/utils/xml_utils.rs
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
- backend/external-services/src/service.rs
- backend/grpc-server/tests/elavon_payment_flows_test.rs
- config/development.toml
Added the Elavon connector code for `Authorzie, Capture, Refunds, PSync, RSync flows.
Generated using AI. 
using `cargo test`
Add the env for api keys
```
export TEST_ELAVON_API_KEY=""
export TEST_ELAVON_API_USER=""
export TEST_ELAVON_API_SECRET=""
```
> feat(connector): Added cards flow and unit tests for elavon

- backend/connector-integration/src/connectors.rs
- backend/connector-integration/src/connectors/checkout.rs
- backend/connector-integration/src/connectors/checkout/transformers.rs
- backend/connector-integration/src/types.rs
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
- backend/grpc-server/tests/checkout_payment_flows_test.rs
- config/development.toml
- examples/example-cli/tests/checkout_grpcurl_test.sh
Added checkout as connector with following flows:
- Authorize
- Capture
- Refund
- PSync
- RSync (tests ignored as its excluded through the server code) will update after fix raised.
- Void
End to End testing is done through `checkout_payment_flows_test.rs`
use cargo test to test `checkout_payment_flows_test.rs`
```
export TEST_CHECKOUT_API_KEY=""
export TEST_CHECKOUT_KEY1=""
export TEST_CHECKOUT_API_SECRET=""
```
- grpcurl result
> feat(connector): Added Authorization flow and tests for checkout

- backend/common_enums/src/enums.rs
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
- backend/domain_types/src/utils.rs
- backend/grpc-server/src/server/payments.rs
> Fix: proto enum fixes

- backend/connector-integration/src/connectors/authorizedotnet.rs
- backend/connector-integration/src/connectors/macros.rs
- backend/connector-integration/src/connectors/phonepe.rs
update expand_fn_handle_response macro with preprocess_response logic
> fix(connector-integration): update expand_fn_handle_response macro with preprocess_response logic

- backend/connector-integration/src/connectors/razorpayv2/transformers.rs
- backend/domain_types/src/types.rs
This PR populates Error details for success(200) responses from razorpay. This happens for genuine user failure cases where razorpay send 2xx response for failed payments in sync. 
Added support for raw_connector_response in Payment Sync Error scenarion.
Create a payment with invaild vpa
```
{
"amount": 1000,
"minor_amount": 1000,
"currency": "INR",
"email": "example@gmail.com",
"payment_method": {
"upi_collect": {
"vpa_id": "success"
}
},
"capture_method": "AUTOMATIC",
"request_ref_id": {
"id": "ref_123{{$timestamp}}"
},
"auth_type": "NO_THREE_DS",
"address": {
"billing": {
"phone": {
"number": "1234567890",
"country_code": "+1"
},
"email": "example@gmail.com"
}
},
"request_incremental_authorization": false,
"enrolled_for_3ds": true,
"browser_info": {
"user_agent": "Mozilla/5.0 …
```
> refactor(connector): [RAZORPAY] populate error for success response in sync

- Cargo.lock
- backend/cards/Cargo.toml
- backend/common_enums/Cargo.toml
- backend/common_utils/Cargo.toml
- backend/connector-integration/Cargo.toml
- backend/domain_types/Cargo.toml
- backend/external-services/Cargo.toml
- backend/grpc-api-types/Cargo.toml
- backend/grpc-server/Cargo.toml
- backend/interfaces/Cargo.toml
Renamed the `cards`, `common_enums` and `common_utils` crate to avoid package collision with Hyperswitch. 
Renamed the `cards`, `common_enums` and `common_utils` crate to `ucs_cards`, `ucs_common_enums` and `ucs_common_utils` respectively in order to avoid package collision with Hyperswitch. 
**Postman Tests**
-Request
```
curl --location 'http://localhost:8080/payments' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'api-key: dev_zYV0Xu6QYgNJZuZOeDHIjfk3DluWR00euuAzMdaMqRxP49SewUCvTsDxUF7Pti1g' \
--data-raw '{
"amount": 6540,
"currency": "USD",
"confirm": true,
"capture_method": "automatic",
"capture_on": "2022-09-10T10:11:12Z",
"amount_to_capture": 6540,
"customer_id": "StripeCustomer",
"email": "guest@example.com",
"name": "John Doe", …
```
> feat(core): Renamed cards, common_enums and common_utils crate

- memory-bank/coderabbit/coderabbit_guidelines.md
Added connector code best practices feedbacks from reviewers to coderabbit guidelines.
> feat(config): Updated Coderabbit Guidelines

- backend/common_utils/src/event_publisher.rs
- backend/grpc-server/Cargo.toml
- backend/grpc-server/src/server/disputes.rs
- backend/grpc-server/src/server/payments.rs
- backend/grpc-server/src/server/refunds.rs
- backend/grpc-server/src/utils.rs
This PR enhances audit event logging by implementing proper data masking
and comprehensive event tracking for better observability and security
compliance.
**Key Changes:**
- Added `masked_serialize()` for all audit event payloads to ensure
sensitive data is properly masked (Given that proto file has secret type)
- Implemented full event JSON logging in event publisher for complete
Kibana visibility
- Enhanced error context with transaction UUID (`txn_uuid`) for improved
debugging
- Fixed missing masking dependencies in grpc-server package
- Updated import statements across all server modules to use correct
masking traits
This change improves the security posture and observability of audit event
logging by ensuring consistent data masking across all event types.
**Root Cause:**
- Audit …
> fix: added masked_serialize for audit events

- backend/connector-integration/src/connectors/mifinity.rs
- backend/connector-integration/src/connectors/mifinity/transformers.rs
- backend/connector-integration/src/utils.rs
- backend/domain_types/src/types.rs
- backend/grpc-server/tests/elavon_payment_flows_test.rs
- backend/grpc-server/tests/fiserv_payment_flows_test.rs
- backend/grpc-server/tests/fiuu_payment_flows_test.rs
- backend/grpc-server/tests/nexinets_payment_flows_test.rs
- backend/grpc-server/tests/noon_payment_flows_test.rs
- backend/grpc-server/tests/novalnet_payment_flows_test.rs
- backend/grpc-server/tests/xendit_payment_flows_test.rs
> fix: razorpay reference id

- Cargo.lock
- Cargo.toml
- backend/cards/Cargo.toml
- backend/common_utils/Cargo.toml
- backend/common_utils/src/consts.rs
- backend/common_utils/src/events.rs
- backend/connector-integration/Cargo.toml
- backend/connector-integration/src/connectors/adyen/test.rs
- backend/connector-integration/src/connectors/razorpay/test.rs
- backend/domain_types/Cargo.toml
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
- backend/external-services/Cargo.toml
- backend/external-services/src/service.rs
- backend/grpc-api-types/Cargo.toml
- backend/grpc-server/Cargo.toml
- backend/grpc-server/src/main.rs
- backend/grpc-server/src/server/disputes.rs
- backend/grpc-server/src/server/payments.rs
- backend/grpc-server/src/utils.rs
- backend/interfaces/Cargo.toml
- config/development.toml
Addition of injector crate being used for proxy payments
Where connector service would want to use user-provided tokens to complete payment in place of the actual values which would be replaced by evternal vault proxy to forward to the actual source.
I tested it with curl 
*Request*
```bash
grpcurl -plaintext \
-H 'x-connector: adyen' \
-H 'x-auth: signature-key' \
-H 'x-vault-proxy-url: VAULT_URL' \
-H 'x-ca-certificate: CERTIFICATE' \
-H 'x-api-key: API_KEY' \
-H 'x-key1: JuspayDEECOM' \
-H 'x-api-secret: API_SECRET' \
-H 'x-merchant-id: reloadhero' \
-H 'x-tenant-id: tenant' \
-d '{
"request_ref_id": {
"id": "ref_1234"
},
"amount": 1000,
"currency": "USD",
"payment_method": {
"card": {
"credit_proxy": {
"card_number": {
"value": "TOKEN"
},
"card_exp_month": {
"value": "{{month}}"
}, …
```
> feat(core): injector crate addition

- .github/workflows/pr-convention-checks.yml
removal of the group in convention check for other PR checks to run fine
> ci(pr-convention-checks): remove concurrency group

- Cargo.lock
- backend/cards/Cargo.toml
- backend/common_utils/Cargo.toml
- backend/connector-integration/Cargo.toml
- backend/domain_types/Cargo.toml
- backend/external-services/Cargo.toml
- backend/grpc-api-types/Cargo.toml
- backend/grpc-server/Cargo.toml
- backend/interfaces/Cargo.toml
Update git reference for hyperswitch
Update git reference for hyperswitch
Without Proxy
```bash
grpcurl -plaintext \
-H 'x-connector: adyen' \
-H 'x-auth: signature-key' \
-H 'x-api-key: API_KEY' \
-H 'x-key1: KEY' \
-H 'x-api-secret: SECRET' \
-H 'x-merchant-id: reloadhero' \
-H 'x-tenant-id: tenant' \
-d '{
"request_ref_id": {
"id": "ref_1234"
},
"amount": 1000,
"currency": "USD",
"payment_method": {
"card": {
"credit": {
"card_number": {
"value": "CARD_NUMBER"
},
"card_exp_month": {
"value": "03"
},
"card_exp_year": {
"value": "2030"
},
"card_cvc": {
"value": "CVC"
},
"card_network": "VISA"
}
}
},
"connector_customer_id": "abc123",
"return_url": "www.google.com",
"capture_method": "1",
"address": {},
"auth_type": "NO_THREE_DS",
"enrolled_for_3ds": true, …
```
> chore: update git tag for hyperswitch repo

- config/production.toml
- config/sandbox.toml
Added Bluecode's base url in sandbox.toml and production.toml
> fix(configs): Add Bluecode's base url in sandbox and production configs

- Cargo.lock
- backend/connector-integration/src/connectors.rs
- backend/connector-integration/src/connectors/dlocal.rs
- backend/connector-integration/src/connectors/dlocal/transformers.rs
- backend/connector-integration/src/types.rs
- backend/domain_types/src/connector_types.rs
- backend/domain_types/src/types.rs
- backend/grpc-server/tests/dlocal_payment_flows_test.rs
- config/development.toml
- config/production.toml
- config/sandbox.toml
Added Dlocal as connector with following flows:
Authorize
Capture
Void
Refund
PSync
RSync
End to End testing is done through dlocal_payment_flows_test.rs
Tests via Hyperswitch
<details>
<summary>Create Payment Dlocal</summary>
```json
{
"amount":100,
"currency": "MYR",
"confirm": true,
"payment_link" : false,
"capture_method": "automatic",
"capture_on": "2022-09-10T10:11:12Z",
"amount_to_capture": 100,
"customer_id": "StripeCustomer",
"email": "guest@example.com",
"name": "John Doe",
"phone": "999999999",
"phone_country_code": "+1",
"description": "Its my first payment request",
"authentication_type": "no_three_ds",
"return_url": "https://google.com",
"payment_method": "card",
"payment_method_type": "credit",
"payment_method_data": {
"card": {
"card_number": "5105105105105100", …
```
> feat(connector): [Dlocal] Connector Integration

- Cargo.lock
- backend/connector-integration/src/connectors/cashfree/transformers.rs
- backend/connector-integration/src/connectors/paytm/transformers.rs
- backend/connector-integration/src/connectors/payu/transformers.rs
- backend/connector-integration/src/connectors/phonepe.rs
- backend/connector-integration/src/connectors/phonepe/transformers.rs
- backend/connector-integration/src/connectors/razorpay/transformers.rs
- backend/connector-integration/src/connectors/razorpayv2/transformers.rs
- backend/domain_types/src/payment_method_data.rs
- backend/domain_types/src/types.rs
This PR introduces the following changes in the PhonePe integration:
1. **Authentication update** : PhonePe authentication now uses only connector credentials. The PhonePe merchant ID is not equivalent to the x-merchant-id header. x-merchant-id is a lineage ID at the client side, sent to UCS, and should not be treated as a connector credential. Instead, the merchant identifier should be taken from the API key in the connector credentials.
2. **New payment method subtype - UPI_QR**: PhonePe supports three UPI flows: UPI Collect, UPI Intent, and UPI QR. In the QR flow, PhonePe provides a base64-encoded QR image along with the intent URL. In the UPI Intent flow, PhonePe only sends the intent URL and does not include the QR image.
3. **Connector transaction ID handling**: The connector …
> refactor(connector): [PHONEPE] refactor phonepe and add UPI_QR support

- .github/workflows/ci.yml
- .nextest.toml
- Makefile
- backend/grpc-server/tests/novalnet_payment_flows_test.rs
The "Run Tests" workflow is a comprehensive testing job that sets up a Rust environment with stable toolchain and Protocol Buffers support, securely downloads and decrypts connector credentials from AWS S3 (when available), and executes the full test suite using nextest with CI-optimized configuration - it includes intelligent handling for fork PRs by gracefully skipping credential-dependent tests when secrets aren't accessible, ensuring both security and functionality across different contribution scenarios.
- Runs on `ubuntu-latest`
- Only executes for pushes to main or PRs from the same repository (security measure)
- Sets `RUSTFLAGS="-D warnings"` to treat warnings as errors
1. __Code checkout__ - Gets the repository code
2. __Rust toolchain setup__ - Installs stable Rust
3. …
> ci: add job to run tests
